arxiv_int:
  target: derived
  outputs:
    derived:
      type: postgres
      host: "{{ env_var('ARXIV_INT_DBT_HOST') }}"
      user: "{{ env_var('ARXIV_INT_DBT_USER') }}"
      password: "{{ env_var('ARXIV_INT_DBT_PASSWORD') }}"
      port: "{{ env_var('ARXIV_INT_DBT_PORT') | as_number }}"
      dbname: "{{ env_var('ARXIV_INT_DBT_DBNAME') }}"
      schema: derived
      threads: "{{ env_var('ARXIV_INT_DBT_THREADS') | as_number }}"
      connect_timeout: 10
      retries: 1
